=== ElkinOsorio23141/TallerXML-Punto6/ListaCursos.dtd
<!ELEMENT ListaCursos (curso)+>
        <!ELEMENT curso (alumno)+>
        <!ELEMENT alumno (DNI, nombre, primer-apellido, segundo-apellido?, ListaAsignaturas)>
        <!ELEMENT ListaAsignaturas (asignatura+)>
        <!ELEMENT asignatura (nombre, profesor)>
        <!ATTLIST asignatura codigo CDATA #REQUIRED>
        <!ELEMENT profesor (NRP, nombre, primer-apellido, segundo-apellido?)>
        <!ELEMENT DNI    (#PCDATA)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT primer-apellido    (#PCDATA)>
        <!ELEMENT segundo-apellido    (#PCDATA)>
        <!ELEMENT NRP    (#PCDATA)>

=== ElkinOsorio23141/TallerXML-Punto6/ListaCursos.xml
<?xml version="1.0" encoding = "UTF-8" standalone="no" ?>
<!DOCTYPE ListaCursos SYSTEM "ListaCursos.dtd">
<ListaCursos>
    <curso>
        <alumno>
            <DNI>1039701773</DNI>
            <nombre>Elkin</nombre>
            <primer-apellido>Osorio</primer-apellido>
            <ListaAsignaturas>
                <asignatura codigo="ING1020">
                    <nombre>CES 3</nombre>
                    <profesor>
                        <NRP>1020</NRP>
                        <nombre>Oscar</nombre>
                        <primer-apellido>Mesa</primer-apellido>
                    </profesor>
                </asignatura>
            </ListaAsignaturas>
        </alumno>
    </curso>
</ListaCursos>
